// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { FlyoutPageProvider } from "./components/(Flyouts)/(Provider)/FlyoutPageContextProvider";
import HeaderCMP from "./components/HeaderCMP";
import { getUserFromSession } from "./(Auth)/lib/session";
import { withFreshRoleFlags } from "./(Auth)/lib/freshRoleFlags";
import { getUnreadMessagesCount } from "./(Auth)/messages/lib/messagesDb";

export const dynamic = 'force-dynamic';


const myFont = localFont({
  src: './fonts/Vazirmatn-RD-FD-Regular.woff2',
})
export const metadata: Metadata = {
	title: "BeyDokht",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// ✅ دریافت اطلاعات کاربر از session
  // پرچم‌های فعال بودن نقش‌ها از دیتابیس خوانده می‌شوند تا پس از تایید یا حذف فروشگاه
  // منوی کناری بدون نیاز به خروج/ورود مجدد به‌روز شود
  const initialUser = await withFreshRoleFlags(await getUserFromSession());

  // ✅ تعداد پیام های خوانده نشده برای نمایش نشانگر در هدر
  const unreadMessagesCount = initialUser?.id ? await getUnreadMessagesCount(initialUser.id) : 0;
	return (
		<html lang="en" className="w-full bg-white">
			<body dir="rtl" className={`${myFont.className} w-full antialiased relative `} >
				
					<FlyoutPageProvider initialUser={initialUser}>
						
						<HeaderCMP unreadMessagesCount={unreadMessagesCount} className="flex sticky header_height  top-1 z-2 items-center    backdrop-blur-sm border-b border-b-gray-400/10 
						landscape:w-full  landscape:lg:px-20 landscape:px-5  shrink-0
						portrait:w-full    portrait:px-4  " />
					
						<div id="content"  className="landscape:w-[85%] portrait:w-full  mx-auto z-1 mt-2">
							{children} 
						</div>
						<footer className="w-full  shrink-0 pb-4 mt-12 z-1">
							<div className="w-full h-[300px] shrink-0 bg-gray-400"></div>
						</footer>
						{/* <div className="fixed top-0 w-full h-[50%]   bg-linear-180 from-sky-600  to-white -z-1"></div> */}
					</FlyoutPageProvider>
				
				
			</body>
		</html>
	);}
